// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func NewApp(ctx context.Context) (*App, func(), error) {
	db := provideDB()
	timePointServer := provideTimePointServer(db)
	app := &App{
		TimePointServer: timePointServer,
		Db:              db,
	}
	return app, func() {
	}, nil
}
